# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michaelscoleri/Documents/Coding/Personal/C++/casino_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michaelscoleri/Documents/Coding/Personal/C++/casino_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelscoleri/Documents/Coding/Personal/C++/casino_project/CMakeFiles /Users/michaelscoleri/Documents/Coding/Personal/C++/casino_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelscoleri/Documents/Coding/Personal/C++/casino_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project01

# Build rule for target.
Project01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Project01
.PHONY : Project01

# fast build rule for target.
Project01/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/build
.PHONY : Project01/fast

Cards.o: Cards.cpp.o
.PHONY : Cards.o

# target to build an object file
Cards.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Cards.cpp.o
.PHONY : Cards.cpp.o

Cards.i: Cards.cpp.i
.PHONY : Cards.i

# target to preprocess a source file
Cards.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Cards.cpp.i
.PHONY : Cards.cpp.i

Cards.s: Cards.cpp.s
.PHONY : Cards.s

# target to generate assembly for a file
Cards.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Cards.cpp.s
.PHONY : Cards.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Game.cpp.s
.PHONY : Game.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Player.cpp.s
.PHONY : Player.cpp.s

Project01.o: Project01.cpp.o
.PHONY : Project01.o

# target to build an object file
Project01.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Project01.cpp.o
.PHONY : Project01.cpp.o

Project01.i: Project01.cpp.i
.PHONY : Project01.i

# target to preprocess a source file
Project01.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Project01.cpp.i
.PHONY : Project01.cpp.i

Project01.s: Project01.cpp.s
.PHONY : Project01.s

# target to generate assembly for a file
Project01.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/Project01.cpp.s
.PHONY : Project01.cpp.s

SlotMachine.o: SlotMachine.cpp.o
.PHONY : SlotMachine.o

# target to build an object file
SlotMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/SlotMachine.cpp.o
.PHONY : SlotMachine.cpp.o

SlotMachine.i: SlotMachine.cpp.i
.PHONY : SlotMachine.i

# target to preprocess a source file
SlotMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/SlotMachine.cpp.i
.PHONY : SlotMachine.cpp.i

SlotMachine.s: SlotMachine.cpp.s
.PHONY : SlotMachine.s

# target to generate assembly for a file
SlotMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/SlotMachine.cpp.s
.PHONY : SlotMachine.cpp.s

blackjack.o: blackjack.cpp.o
.PHONY : blackjack.o

# target to build an object file
blackjack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/blackjack.cpp.o
.PHONY : blackjack.cpp.o

blackjack.i: blackjack.cpp.i
.PHONY : blackjack.i

# target to preprocess a source file
blackjack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/blackjack.cpp.i
.PHONY : blackjack.cpp.i

blackjack.s: blackjack.cpp.s
.PHONY : blackjack.s

# target to generate assembly for a file
blackjack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project01.dir/build.make CMakeFiles/Project01.dir/blackjack.cpp.s
.PHONY : blackjack.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Project01"
	@echo "... Cards.o"
	@echo "... Cards.i"
	@echo "... Cards.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Project01.o"
	@echo "... Project01.i"
	@echo "... Project01.s"
	@echo "... SlotMachine.o"
	@echo "... SlotMachine.i"
	@echo "... SlotMachine.s"
	@echo "... blackjack.o"
	@echo "... blackjack.i"
	@echo "... blackjack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

